from __future__ import annotations

import pathlib

from xia2.Modules.Laue_TOF.laue_tof_report import (
    normalisation_plot,
    parse_lambdanorm,
)

# The shape lawless writes: a gnuplot script with the numbers in named inline
# data blocks, $LAMBDANORM (wavelength, w, relative uncertainty, w low, w high)
# and $LAMBDABINS (wavelength, w, sigma).
LAMBDANORM = """\
# LAMBDANORM - Laue wavelength normalization curve
# Generated by LAWLESS 0.0.1
set title "Laue wavelength normalization (GP)"
set xrange [2.229:2.281]

$LAMBDANORM << EOD
     2.229      1.0291    0.016544      1.0121      1.0461
     2.255      1.0293    0.015569      1.0133      1.0453
     2.281      1.0303    0.014671      1.0151      1.0454
EOD

$LAMBDABINS << EOD
     2.240      1.0300    0.020000
     2.270      1.0280    0.021000
EOD

plot $LAMBDANORM using 1:2 with lines
"""


def test_parse_lambdanorm(tmp_path: pathlib.Path):
    """Both data blocks are read, and the gnuplot around them ignored."""
    path = tmp_path / "LAMBDANORM"
    path.write_text(LAMBDANORM)

    blocks = parse_lambdanorm(path)

    assert set(blocks) == {"LAMBDANORM", "LAMBDABINS"}
    assert len(blocks["LAMBDANORM"]) == 3
    assert len(blocks["LAMBDABINS"]) == 2
    assert blocks["LAMBDANORM"][0] == [2.229, 1.0291, 0.016544, 1.0121, 1.0461]
    assert blocks["LAMBDABINS"][-1] == [2.270, 1.0280, 0.021000]


def test_normalisation_plot(tmp_path: pathlib.Path):
    """The curve, its uncertainty band and the fitted bins become one plot."""
    path = tmp_path / "LAMBDANORM"
    path.write_text(LAMBDANORM)

    plot = normalisation_plot(path)

    assert plot is not None
    names = [trace["name"] for trace in plot["data"]]
    assert names == ["1 sigma", "w(lambda)", "binned observations"]
    band, curve, bins = plot["data"]
    # The band goes up one edge and back along the other, so it closes
    assert len(band["x"]) == 6
    assert band["fill"] == "toself"
    assert curve["y"] == [1.0291, 1.0293, 1.0303]
    assert bins["error_y"]["array"] == [0.02, 0.021]
    assert plot["layout"]["xaxis"]["title"] == "Wavelength (A)"


def test_normalisation_plot_without_a_curve(tmp_path: pathlib.Path):
    """A file with no curve in it gives no plot, rather than an empty one."""
    path = tmp_path / "LAMBDANORM"
    path.write_text('# nothing here\nset title "empty"\n')

    assert normalisation_plot(path) is None
    assert parse_lambdanorm(path) == {}
